---
# Non-secret configuration for tunnel_hosts
timezone: "America/New_York"

security_ssh_config_path: /etc/ssh/sshd_config
security_sshd_name: sshd

security_ssh_port: 7822
security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"
security_ssh_permit_empty_password: "no"
security_ssh_challenge_response_auth: "no"
security_ssh_gss_api_authentication: "no"
security_ssh_x11_forwarding: "no"
security_sshd_state: started
security_ssh_restart_handler_state: restarted
security_ssh_allowed_users: 
  - deployUser
security_ssh_allowed_groups: []

security_sudoers_passwordless: []
security_sudoers_passworded: []

security_autoupdate_enabled: true
security_autoupdate_blacklist: []
security_autoupdate_additional_origins: []

security_fail2ban_enabled: true
security_fail2ban_custom_configuration_template: "jail.local.j2"