---
# Non-secret configuration for tunnel_hosts
timezone: "America/New_York"
domain: "mclaysen.com"
email_address: "me@mclaysen.com"

deploy_user_name: "deployUser"
deployuser_ssh_public_key_path: "/Users/mclaysen/.ssh/deployuser_vps_tunnel.pub"

security_ssh_config_path: /etc/ssh/sshd_config
security_sshd_name: sshd

security_ssh_port: 7822
security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"
security_ssh_permit_empty_password: "no"
security_ssh_challenge_response_auth: "no"
security_ssh_gss_api_authentication: "no"
security_ssh_x11_forwarding: "no"
security_sshd_state: started
security_ssh_restart_handler_state: restarted
security_ssh_allowed_users: 
  - "{{ deploy_user_name }}"
security_ssh_allowed_groups: []

security_sudoers_passwordless:
  - "{{ deploy_user_name }}"
security_sudoers_passworded: []

security_autoupdate_enabled: true
security_autoupdate_blacklist: []
security_autoupdate_additional_origins: []

firewall_ports:
  - 80/tcp
  - 443/tcp
  - 51820/udp
  - 21820/udp
  - "{{ security_ssh_port }}/tcp"

# Pangolin installer configuration
pangolin_base_domain: "example.com"
pangolin_dashboard_domain: "pangolin.example.com"
pangolin_install_gerbil: "yes"