$ANSIBLE_VAULT;1.1;AES256
31656139363535306236393235643030313665333533383830383434663439656432306636306564
3038613562376565363936373433356263653532343338350a336631633230326666633161353837
61343462386662613766306337626434323432623533303132663334666435633864303331356139
6435393435353833620a633362623038323565633165323039373331633536643933643634663437
63303066653239653830396633346137616166383335623339313664313632313837623432366631
66303031613439646463303639663633353938343638653336303861653861663032343862323632
39643161613631643035366433353666326464623436336236643835313535663863613735313139
38343963343862623436663833333735363034663364343063326431313636363731386365653561
38333232303836643563393239616663623334316365653039326166313332656233376535333139
3764373133393565363964383262653537356232616664626263
