$ANSIBLE_VAULT;1.1;AES256
39386538613766336535643137393261383638353163613961336134396139326430613566356135
6336663832343461646235306333376265363362326139360a613433643539303262666363353633
34393732656266666632386131303834633533333038346130656363343632306435303164376565
3362613635653131350a363532626438333832353431613864363431356362626439373936323062
32336661613364626263666537313632313261636135333835353536393438663865303165393631
37626631313466633563616561303861663266306563373965303837323364363465643037363466
32363434393561326338666461653032346533373865303963316531656664316564303937313736
64316462323764383435353664393936323730333761646362373835356665623061356566373161
34333236346231326661646263636366316535393938313836633432653062643930333531373264
64323364393431326261383533623036636638653534396339623736346439323339653061366534
31333136363139356163303030333239376161363863316234643966346263343831303565633831
31373834633764373961613831326238306663623131313639623535316132393334316630663533
34376539343262333539633464643536383666303930323066363630633930323135626664303631
61386264646234366434353036653432376538366231636139346639666532656630393762643639
32363635363931333838396639666532656363613034303566633064353666313635633435363431
38326361633130643030363438303766633335646436366464396233646164623266386431383438
62613163383436653263353862363065383533366331653836386231313336623332323235636436
35626464623566613638343831613861386461663030623365363863313130346634643832383730
39306433303566653564363561396134356436356163363937613332636361343665356464646637
61386166326631306135613835643661303036643330386261663663353530366639656666316162
38646137636163303334376332343032386162383761353330323961346161346365653631616338
3230333530393066303536626662653738303335373533386137
