$ANSIBLE_VAULT;1.1;AES256
65383533383432373536646163323864396239363731306130313761346464313438343735366462
3035326239336263616239653762383934383335663635340a323932313061313164366266373763
33643635323664373637313838346535616533313763356264303762316665393830303866316536
6461306530616561630a313033303637323461393065653763303639376335633339623034386161
31653463643138346534366435356239313232393733366131613065323132663832333630653532
65393933616332386661616134333837393561316466663261346331393666373365356566623636
62303131313464343064336337626530626232323462623265643432353562343637343936396161
37636233666635366337366331643037626164613537653666656234356163613031633935313838
36356361646364613739616562376539343030326666366534373264623037656666326335346331
33346234633135623139333635333133306666373738633331666262636432393233353038383166
62303638666435373430326235623763633537613263366137653039653837336536343462303038
30313538613939366164383132613664623433636462303435326234363663393361333837336664
63326531396461393666646161393536643565653530626336636635363166326637393239323133
64386131663563656364323865383936326266343735646662393034626230306461336463353338
64656134366164316535363834633338376430636164386435333431666333393637333366363733
31346565373232616366326434353036363565633461333537646635303035343133363937393962
39386331623562613662623937616434643563346265623833633366623431653961643262303337
35646463643630656337663337323039306339303536356265383164343837343266643831346661
363638313834393630353963366137383763
