$ANSIBLE_VAULT;1.1;AES256
35613963643664383739643837643965633162306631633831383033623564386535383332666333
6135366661616236343863633763623334303337636132390a373463346331626261343832383434
30623535303738306234343561326261373165346236336365393636313963333962313130353664
3136353138383735660a623430613635326439363538353866646665306232323539343737613830
65666237316461666462326432386138363466396637623934306161383531383633393932633839
33336530663734616239633338396266653034653832356463386237616264666230306430383466
33303961386565633066373236373132376563356265353631333833373330613532646532373730
32386531653464313832336533653866373836396135643030323932393862336432353561333439
66636134313935643234376665616561626135313364333766643231633732346139316435376438
30626336336331353130383635313736343263343433313063326235616137636564666236323836
64316338333531383732396432386238323334633464343932326232306161336263373965386366
63306564366338333732663739356437313861626630373332643061623630643564363336616465
35366138623038353464626362336630666637333335363338373038373239623930656566663266
32326335383662383339303036313232363861316439643362633738386432653963376630373230
61636265346136653235663837313037323932636635343763363761313862333163653666376639
64353131323731346664616462613063626638316265376438373132396438333338376636316562
33633530343962363332373836636637393266353134613966323836336237656437333934373936
36303462353663356435386565646630663030633636663933636330343234323539363531633033
333762393031323634633936646232356164
