$ANSIBLE_VAULT;1.1;AES256
64323537656537323031396339336365316164663137636534663662663634313564653238646164
3237356164666334313161643365393263376265373364310a306630386331383438313237363031
64353966363038653064393261316539316266313763323364353465393962373531306562316232
6631346237343661330a343637326538386362373665303266656437316338366261626132643238
38626661363234346662366630363839633439666239356435636639316437363038643435656134
66393163656238343436353530346530303864626234333463623063303139386661376265656365
32373139356532643165313333666239313666636331633065323064333763313664643332393963
62343736616565323738636336346366323666396634306661373738656361623336376235373934
65373939633233663666353464386533636463316465353862313939353631306439316163346166
37663962326639316532636433623632653132393738363332623531626430613533313337653237
61666534623839303931666362366335313534316564343137623930346335633232363366343539
33623038643763316630663736313661323531366634613563363966623030386237316134343463
35333632386538623638373062643763343335326633353263626363623639656335636237323865
63373361663863313563653032326362616233616130663030373830373165616465343464393864
63636538373265633738363363353566656537346333636661336430333362663966633830646664
62373565323461313736353436323930616639616431643033326463373161613638653934653431
37393865393662616130663165343565323939336130653238326538613662633130613735333465
35316132393230626166666431616635303135316536656337393735366531626363366532343933
66323532306437646335663037653234326464383732396232346562666338663233323933356535
64326362363166393965643132396438393965393538633430353836373036326661396134616638
37666264333861303462356238366331383837383433623838383865616362303233653730373261
3030373030356661653431646165346639646131643534326566
