# Non-secret configuration values
timezone: America/New_York
domain: mclaysen.com
username: mclaysen
node_exporter_version: 1.10.2
cadvisor_listen_ip: 172.17.0.1
cadvisor_port: 8080
cadvisor_version: 0.55.1