$ANSIBLE_VAULT;1.1;AES256
64653037646432343362623736313263633263343962663565393736393236356232383663353262
6439383037393261313639306264666232323563646130370a333464653062666166373932613464
30313131663731613130343935356265393165643662653335666662393965616131366630346439
3236663466613732640a623864356663656238346535313634623564663564643734663938366165
6666
