$ANSIBLE_VAULT;1.1;AES256
36333565373434303363363933363233363330623732373435613637323361363931396131653439
3062323938353939666230613264353761653231306433340a316462393464396264373631656335
39383236656335353662353530653538633164366234306132383564633636333563323431353462
3264303663386264390a653164623064616262306534336633643364663365376330616139333461
66356133343231323565666564353839653135346361636536636366353466666663663337613262
36366337636132666332613364313961396265353766626635656132343830616331343463656533
35376332666632393063313963396234613162346161373537373366623731353964306665356437
63353164306336393039353439363434393333353264373366373633633635346263376436643264
30616666636635336436396365373736336161326166353964663162333366626635346339393839
30346334366466363032363737633336366365303032323539326539386363363030623032363233
39393366633565313531353361396236383238663930353837376362363337393763313131363764
65393663396562373436316235643161323265353564356136626431643533623036336234613166
6662
