---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart ssh
  ansible.builtin.service:
    name: "{{ security_sshd_name }}"
    state: "{{ security_ssh_restart_handler_state }}"

- name: restart firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: restarted
    enabled: true