---
- name: Bootstrap VPS
  hosts: tunnel_hosts
  become: true
  vars:
    node_exporter_version: 1.10.2
  tasks:
    - name: Install Node Exporter
      ansible.builtin.include_role:
        name: geerlingguy.node_exporter

- name: Deploy cadvisor for monitoring docker
  hosts: tunnel_hosts
  become: true
  vars:
    cadvisor_listen_ip: "172.17.0.1"
    cadvisor_port: 8080
    cadvisor_version: "0.55.1"
  tasks:
    - name: Setup consul
      ansible.builtin.include_role:
        name: prometheus.prometheus.cadvisor